import { stepCountIs, streamText } from "ai";
import { z } from "zod";
import { modelProvider } from "@/lib/providers/model";
import { EvidenceStore, ToolCallBudget } from "@/lib/research/evidence";
import { createResearchTools } from "@/lib/research/tools";
import { RESEARCH_CORE_PROMPT } from "@/lib/research/core";
import { getSkill } from "@/lib/skills/loader";
import { routeSkills } from "@/lib/skills/routing";
import { MODEL_CALL_TIMEOUT_MS } from "@/lib/research/limits";
import { quickEvidenceFallback } from "@/lib/research/quick-fallback";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { addConversationMessage, conversationContext, ensurePersistentThread, saveQuickEvent, saveQuickRouting } from "@/lib/research/postgres-conversations";
const schema = z.object({ threadId: z.string().uuid().optional(), message: z.string().trim().min(1).max(4000) }); const encoder = new TextEncoder(); const line = (value: unknown) => encoder.encode(`${JSON.stringify(value)}\n`);
export async function POST(request: Request) {
  const parsed = schema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Invalid chat request" }, { status: 400 }); if (!modelProvider.configured("FAST")) return Response.json({ error: "Quick chat requires OPENROUTER_API_KEY and MODEL_FAST." }, { status: 503 });
  const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return Response.json({ error: "Authentication required" }, { status: 401 });
  const setup = await (async () => { const thread = await ensurePersistentThread(supabase, user.id, parsed.data.threadId, parsed.data.message); const history = await conversationContext(supabase, user.id, thread.id); await addConversationMessage(supabase, user.id, thread.id, "user", parsed.data.message); const route = await routeSkills(parsed.data.message, history); await saveQuickRouting(supabase, user.id, thread.id, route); return { thread, history, route }; })().catch(error => error instanceof Error ? error : new Error("Could not initialize Quick Chat"));
  if (setup instanceof Error) return Response.json({ error: setup.message }, { status: 503 });
  const { thread, history, route } = setup;
  if (route.clarification && Math.max(...route.selections.map(item => item.confidence), 0) < .7) { await addConversationMessage(supabase, user.id, thread.id, "assistant", route.clarification); await saveQuickEvent(supabase, user.id, thread.id, "quick.clarification", {}); return new Response(line({ type: "clarification", threadId: thread.id, text: route.clarification }), { headers: { "Content-Type": "application/x-ndjson; charset=utf-8" } }); }
  const skills = route.selections.map(item => getSkill(item.skillId)); const evidence = new EvidenceStore(8); const allowlist = [...new Set(skills.flatMap(skill => skill.tools))]; const { tools, unavailable } = createResearchTools(allowlist, { evidence, calls: new ToolCallBudget(2) });
  const result = streamText({ model: modelProvider.model("FAST"), tools, stopWhen: stepCountIs(3), prepareStep: ({ stepNumber }) => stepNumber >= 2 ? { toolChoice: "none" } : undefined, maxRetries: 1, abortSignal: AbortSignal.timeout(MODEL_CALL_TIMEOUT_MS), system: `${RESEARCH_CORE_PROMPT}\n\n${skills.map(skill => `${skill.instructions}\n${skill.quickPrompt}\n${skill.disclaimer}`).join("\n\n")}\nUnavailable tools: ${unavailable.join(", ") || "none"}.`, messages: [...history.map(item => ({ role: item.role as "user" | "assistant", content: item.content })), { role: "user" as const, content: parsed.data.message }] });
  let answer = ""; const body = new ReadableStream<Uint8Array>({ async start(controller) { controller.enqueue(line({ type: "thread", threadId: thread.id })); controller.enqueue(line({ type: "status", state: "thinking", message: "Jarvis is thinking…" })); try { for await (const part of result.fullStream) { if (part.type === "tool-call") controller.enqueue(line({ type: "status", state: "searching", message: "Gathering evidence…" })); else if (part.type === "tool-result") controller.enqueue(line({ type: "status", state: "writing", message: "Reviewing evidence…" })); else if (part.type === "text-delta") { answer += part.text; controller.enqueue(line({ type: "text", text: part.text })); } else if (part.type === "error") throw part.error; } if (!answer.trim()) { const fallback = quickEvidenceFallback(evidence.all()); if (!fallback) throw new Error("The model completed without producing an answer. Please retry shortly."); answer = fallback; controller.enqueue(line({ type: "text", text: fallback })); await saveQuickEvent(supabase, user.id, thread.id, "quick.degraded", { reason: "empty_model_answer", sourceCount: evidence.all().length }); } const sources = evidence.all().map(source => ({ id: source.id, title: source.title, url: source.canonicalUrl, publisher: source.publisher, retrievedAt: source.retrievedAt })); controller.enqueue(line({ type: "citations", sources })); controller.enqueue(line({ type: "done" })); await addConversationMessage(supabase, user.id, thread.id, "assistant", answer); await saveQuickEvent(supabase, user.id, thread.id, "quick.completed", { sourceCount: sources.length }); } catch (error) { const message = error instanceof Error ? error.message : "The model request failed"; await saveQuickEvent(supabase, user.id, thread.id, "quick.failed", { error: message }); controller.enqueue(line({ type: "error", message })); } finally { controller.close(); } } }); return new Response(body, { headers: { "Content-Type": "application/x-ndjson; charset=utf-8", "Cache-Control": "no-store" } });
}
