create extension if not exists pgcrypto;
create type public.research_mode as enum ('stocks', 'travel', 'shopping');
create type public.run_status as enum ('needs_input', 'queued', 'running', 'partial', 'completed', 'failed', 'cancelled');

create table public.stock_watchlist_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, ticker text not null, company_name text, created_at timestamptz not null default now(), unique(user_id, ticker));
create table public.saved_trips (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, destination text not null, start_date date, end_date date, passengers int not null default 1 check(passengers > 0), constraints jsonb not null default '{}', created_at timestamptz not null default now());
create table public.tracked_products (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, public_url text, description text, target_price numeric, currency text, created_at timestamptz not null default now(), check(public_url is not null or description is not null));
create table public.hub_snapshots (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, hub research_mode not null, card_type text not null, tracked_item_id uuid, data jsonb not null, provider text not null, retrieved_at timestamptz not null, expires_at timestamptz not null, error text, created_at timestamptz not null default now());
create table public.threads (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, mode research_mode not null, title text not null, tracked_item_id uuid, created_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, thread_id uuid not null references public.threads on delete cascade, role text not null check(role in ('user','assistant')), content text not null, created_at timestamptz not null default now());
create table public.research_runs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, thread_id uuid references public.threads on delete set null, mode research_mode not null, query text not null, status run_status not null default 'queued', idempotency_key text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, idempotency_key));
create table public.normalized_sources (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, run_id uuid not null references public.research_runs on delete cascade, canonical_url text not null, title text not null, publisher text, published_at timestamptz, retrieved_at timestamptz not null, excerpt text, source_type text not null, unique(run_id, canonical_url));
create table public.specialist_results (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, run_id uuid not null references public.research_runs on delete cascade, specialist_id text not null, status text not null, findings jsonb not null default '[]', error text, unique(run_id, specialist_id));
create table public.research_reports (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, run_id uuid not null references public.research_runs on delete cascade, version int not null default 1, report jsonb not null, fresh_at timestamptz not null, created_at timestamptz not null default now(), unique(run_id, version));

do $$ declare t text; begin foreach t in array array['stock_watchlist_items','saved_trips','tracked_products','hub_snapshots','threads','messages','research_runs','normalized_sources','specialist_results','research_reports'] loop execute format('alter table public.%I enable row level security', t); execute format('create policy "owner access" on public.%I for all using (auth.uid() = user_id) with check (auth.uid() = user_id)', t); end loop; end $$;
create index hub_snapshots_lookup on public.hub_snapshots(user_id, hub, card_type, expires_at desc);
create index research_runs_owner_status on public.research_runs(user_id, status, created_at desc);
