alter table public.threads add column skill_ids text[] not null default '{}';
update public.threads set skill_ids = array[case mode::text when 'stocks' then 'stock-analysis' when 'travel' then 'travel-planning' else 'product-research' end];
alter table public.threads drop column mode;
alter table public.research_runs add column skill_ids text[] not null default '{}', add column plan jsonb not null default '{}';
update public.research_runs set skill_ids = array[case mode::text when 'stocks' then 'stock-analysis' when 'travel' then 'travel-planning' else 'product-research' end];
alter table public.research_runs drop column mode;
alter table public.hub_snapshots add column skill_id text;
update public.hub_snapshots set skill_id = case hub::text when 'stocks' then 'stock-analysis' when 'travel' then 'travel-planning' else 'product-research' end;
alter table public.hub_snapshots alter column skill_id set not null, drop column hub;
drop index if exists public.hub_snapshots_lookup;
create index dashboard_snapshots_lookup on public.hub_snapshots(user_id, skill_id, card_type, expires_at desc);
create table public.routing_decisions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, thread_id uuid not null references public.threads on delete cascade, run_id uuid references public.research_runs on delete cascade, selected_skill_ids text[] not null, candidates jsonb not null default '[]', rationale jsonb not null default '{}', router_model text, used_fallback boolean not null default false, created_at timestamptz not null default now());
create table public.execution_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, thread_id uuid not null references public.threads on delete cascade, run_id uuid references public.research_runs on delete cascade, event_type text not null, detail jsonb not null default '{}', created_at timestamptz not null default now());
alter table public.routing_decisions enable row level security;
alter table public.execution_events enable row level security;
create policy "owner access" on public.routing_decisions for all using (auth.uid() = user_id) with check(auth.uid() = user_id);
create policy "owner access" on public.execution_events for all using (auth.uid() = user_id) with check(auth.uid() = user_id);
create index routing_decisions_thread on public.routing_decisions(user_id, thread_id, created_at desc);
create index execution_events_thread on public.execution_events(user_id, thread_id, created_at);
drop type if exists public.research_mode;
